[package]
name = "abc193_c"
version = "0.1.0"
authors = ["hikaru7719 <j148016s@st.u-gakugei.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }